# -*- coding: utf-8 -*-
"""C1_W3_Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/https-deeplearning-ai/tensorflow-1-public/blob/adding_C1/C1/W3/assignment/C1_W3_Assignment.ipynb
"""

#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""In the videos you looked at how you would improve Fashion MNIST using Convolutions. For your exercise see if you can improve MNIST to 99.8% accuracy or more using only a single convolutional layer and a single MaxPooling 2D. You should stop training once the accuracy goes above this amount. It should happen in less than 20 epochs, so it's ok to hard code the number of epochs for training, but your training must end once it hits the above metric. If it doesn't, then you'll need to redesign your layers.

I've started the code for you -- you need to finish it!

When 99.8% accuracy has been hit, you should print out the string "Reached 99.8% accuracy so cancelling training!"

**Things to Note:**
1. When coding the `class myCallback`, Python 3 will run into an error
```python
TypeError: '>' not supported between instances of 'NoneType' and 'float'
```
when using the code
```python
if(logs.get('accuracy')>0.99):
```

For Python 3, use the following equivalent code line

```python
if logs.get('accuracy') is not None and logs.get('accuracy') > 0.99:
```

2. You can run the notebook using TensorFlow 2.5.0
"""

#!pip install tensorflow==2.5.0

import tensorflow as tf

print(tf.__version__)

mnist = tf.keras.datasets.mnist
(_,_), (test_images, test_labels) = mnist.load_data()
test_images = test_images/255.0
test_images.shape

# GRADED FUNCTION: train_mnist_conv
def train_mnist_conv():
    # Please write your code only where you are indicated.
    # please do not remove model fitting inline comments.

    # YOUR CODE STARTS HERE
    class mycallback(tf.keras.callbacks.Callback):
      def on_epoch_end(self, epoch, logs = {}):
        if(logs.get('accuracy') is not None and logs.get('accuracy')>0.998):
          print('\nReach 99.8% accuracy!, so canceling training')
          self.model.stop_training = True
    
    # YOUR CODE ENDS HERE

    mnist = tf.keras.datasets.mnist
    (training_images, training_labels), (test_images, test_labels) = mnist.load_data()
   
    # YOUR CODE STARTS HERE
    training_images = training_images/255.0
    test_images = test_images/255.0

    # YOUR CODE ENDS HERE
    global model
    model = tf.keras.models.Sequential([
            tf.keras.layers.Conv2D(64, (3,3), activation = 'relu', input_shape = (28,28,1)),
            tf.keras.layers.MaxPooling2D((2,2)),
            tf.keras.layers.Flatten(),
            tf.keras.layers.Dense(120, activation = 'relu'),
            tf.keras.layers.Dense(10, activation = 'softmax'),
    ])

    model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
    callbacks = mycallback()
    # model fitting
    history = model.fit(training_images,training_labels, epochs=20, callbacks = [callbacks])    # model fitting
    #print(model.evaluate(test_images, test_labels))
    return history.epoch, history.history['accuracy'][-1], model

_, _,model= train_mnist_conv()

model.summary()

loss, accuracy =model.evaluate(test_images, test_labels)

print('test accuracy: {}'.format(accuracy))

import matplotlib.pyplot as plt
plt.imshow(test_images[3])
print(test_labels[3])

